"""
src/modules/analytics.py
------------------------
Business Analytics Calculation Module.

Contains pure, reusable Pandas data analysis functions that calculate key performance
indicators (KPIs), metric aggregations, breakdown tables, and customer rankings.

All functions accept a Pandas DataFrame (cleaned sales dataset) and return primitive
values (float, int) or aggregated DataFrames ready for UI visualization.
"""

from typing import Optional
import pandas as pd
import numpy as np


def get_total_sales(df: pd.DataFrame) -> float:
    """
    Purpose: Calculates the gross revenue across all records.
    Returns: Total sales sum as float.
    """
    if df.empty or "Sales" not in df.columns:
        return 0.0
    return float(df["Sales"].sum())


def get_total_profit(df: pd.DataFrame) -> float:
    """
    Purpose: Calculates the total net profit achieved across all records.
    Returns: Total profit sum as float.
    """
    if df.empty or "Profit" not in df.columns:
        return 0.0
    return float(df["Profit"].sum())


def get_total_orders(df: pd.DataFrame) -> int:
    """
    Purpose: Counts total unique order transactions.
    Returns: Number of unique Order_IDs.
    """
    if df.empty or "Order_ID" not in df.columns:
        return 0
    return int(df["Order_ID"].nunique())


def get_customer_count(df: pd.DataFrame) -> int:
    """
    Purpose: Counts total unique active customer accounts.
    Returns: Number of unique Customer_IDs.
    """
    if df.empty or "Customer_ID" not in df.columns:
        return 0
    return int(df["Customer_ID"].nunique())


def get_average_order_value(df: pd.DataFrame) -> float:
    """
    Purpose: Calculates Average Order Value (AOV = Total Sales / Total Orders).
    Returns: Average revenue per order as float.
    """
    orders = get_total_orders(df)
    if orders == 0:
        return 0.0
    sales = get_total_sales(df)
    return round(sales / orders, 2)


def get_sales_by_month(df: pd.DataFrame) -> pd.DataFrame:
    """
    Purpose: Aggregates sales and profit chronologically by Month.
    Returns: DataFrame with columns ['YearMonth', 'Month_Name', 'Sales', 'Profit'].
    """
    if df.empty or "Order_Date" not in df.columns:
        return pd.DataFrame(columns=["YearMonth", "Month_Name", "Sales", "Profit"])

    temp_df = df.copy()
    temp_df["YearMonth"] = temp_df["Order_Date"].dt.to_period("M").astype(str)
    temp_df["Month_Name"] = temp_df["Order_Date"].dt.strftime("%b %Y")

    monthly_df = (
        temp_df.groupby(["YearMonth", "Month_Name"])[["Sales", "Profit"]]
        .sum()
        .reset_index()
        .sort_values(by="YearMonth")
    )
    return monthly_df


def get_sales_by_product(df: pd.DataFrame, top_n: Optional[int] = None) -> pd.DataFrame:
    """
    Purpose: Aggregates total sales, quantity sold, and profit grouped by Product.
    Returns: DataFrame sorted by Sales descending. Option to limit to top N products.
    """
    if df.empty or "Product" not in df.columns:
        return pd.DataFrame(columns=["Product", "Sales", "Quantity", "Profit"])

    prod_df = (
        df.groupby("Product")[["Sales", "Quantity", "Profit"]]
        .sum()
        .reset_index()
        .sort_values(by="Sales", ascending=False)
    )

    if top_n and top_n > 0:
        prod_df = prod_df.head(top_n)

    return prod_df.reset_index(drop=True)


def get_sales_by_category(df: pd.DataFrame) -> pd.DataFrame:
    """
    Purpose: Aggregates total sales, profit, and calculates category profit margins.
    Returns: DataFrame with columns ['Category', 'Sales', 'Profit', 'Profit_Margin_%'].
    """
    if df.empty or "Category" not in df.columns:
        return pd.DataFrame(columns=["Category", "Sales", "Profit", "Profit_Margin_%"])

    cat_df = df.groupby("Category")[["Sales", "Profit"]].sum().reset_index()
    cat_df["Profit_Margin_%"] = np.where(
        cat_df["Sales"] > 0, np.round((cat_df["Profit"] / cat_df["Sales"]) * 100, 2), 0.0
    )
    return cat_df.sort_values(by="Sales", ascending=False).reset_index(drop=True)


def get_sales_by_region(df: pd.DataFrame) -> pd.DataFrame:
    """
    Purpose: Aggregates total sales and regional contribution percentage.
    Returns: DataFrame with columns ['Region', 'Sales', 'Profit', 'Sales_Share_%'].
    """
    if df.empty or "Region" not in df.columns:
        return pd.DataFrame(columns=["Region", "Sales", "Profit", "Sales_Share_%"])

    reg_df = df.groupby("Region")[["Sales", "Profit"]].sum().reset_index()
    total_sales = reg_df["Sales"].sum()

    reg_df["Sales_Share_%"] = np.where(
        total_sales > 0, np.round((reg_df["Sales"] / total_sales) * 100, 2), 0.0
    )
    return reg_df.sort_values(by="Sales", ascending=False).reset_index(drop=True)


def get_profit_by_product(df: pd.DataFrame, top_n: Optional[int] = None) -> pd.DataFrame:
    """
    Purpose: Aggregates net profit generated by individual products.
    Returns: DataFrame sorted by Profit descending. Option to limit to top N products.
    """
    if df.empty or "Product" not in df.columns:
        return pd.DataFrame(columns=["Product", "Profit", "Sales"])

    profit_df = (
        df.groupby("Product")[["Profit", "Sales"]]
        .sum()
        .reset_index()
        .sort_values(by="Profit", ascending=False)
    )

    if top_n and top_n > 0:
        profit_df = profit_df.head(top_n)

    return profit_df.reset_index(drop=True)


def get_profit_by_region(df: pd.DataFrame) -> pd.DataFrame:
    """
    Purpose: Aggregates regional net profit and calculates regional profit margins.
    Returns: DataFrame sorted by Profit descending.
    """
    if df.empty or "Region" not in df.columns:
        return pd.DataFrame(columns=["Region", "Profit", "Sales", "Profit_Margin_%"])

    reg_profit = df.groupby("Region")[["Profit", "Sales"]].sum().reset_index()
    reg_profit["Profit_Margin_%"] = np.where(
        reg_profit["Sales"] > 0, np.round((reg_profit["Profit"] / reg_profit["Sales"]) * 100, 2), 0.0
    )
    return reg_profit.sort_values(by="Profit", ascending=False).reset_index(drop=True)


def get_top_customers(df: pd.DataFrame, n: int = 10) -> pd.DataFrame:
    """
    Purpose: Ranks top N customers by total monetary spend, profit, and order count.
    Returns: DataFrame with Customer_ID, Customer_Name, Total_Sales, Total_Profit, Order_Count.
    """
    if df.empty or "Customer_ID" not in df.columns:
        return pd.DataFrame(
            columns=["Customer_ID", "Customer_Name", "Total_Sales", "Total_Profit", "Order_Count"]
        )

    cust_df = (
        df.groupby(["Customer_ID", "Customer_Name"])
        .agg(
            Total_Sales=("Sales", "sum"),
            Total_Profit=("Profit", "sum"),
            Order_Count=("Order_ID", "nunique"),
        )
        .reset_index()
        .sort_values(by="Total_Sales", ascending=False)
    )
    return cust_df.head(n).reset_index(drop=True)


def calculate_business_health_score(df: pd.DataFrame) -> dict:
    """Calculates a transparent Business Health Score (0-100) combining 4 weighted components:
    1. Revenue Growth (30% weight)
    2. Profitability Margin (30% weight)
    3. Customer Retention Rate (20% weight)
    4. Catalog Profitability Consistency (20% weight)
    """
    if df.empty:
        return {"health_score": 0, "status": "Critical", "components": {}}

    total_sales = get_total_sales(df)
    total_profit = get_total_profit(df)

    # 1. Profitability Score (Margin %)
    profit_margin = (total_profit / total_sales * 100) if total_sales > 0 else 0
    prof_score = min(100, max(0, int(profit_margin * 3.5)))

    # 2. Revenue Growth Score
    monthly_df = get_sales_by_month(df)
    if len(monthly_df) >= 2:
        last_m = monthly_df.iloc[-1]["Sales"]
        prev_m = monthly_df.iloc[-2]["Sales"]
        growth_pct = ((last_m - prev_m) / prev_m * 100) if prev_m > 0 else 0
        rev_score = min(100, max(0, int(75 + growth_pct * 1.2)))
    else:
        rev_score = 80

    # 3. Customer Retention Score
    cust_df = df.groupby("Customer_ID")["Order_ID"].nunique()
    repeat_pct = (cust_df > 1).mean() * 100 if len(cust_df) > 0 else 0
    retention_score = min(100, max(0, int(repeat_pct)))

    # 4. Catalog Profitability Consistency
    prod_df = get_sales_by_product(df)
    if not prod_df.empty:
        profitable_prods = (prod_df["Profit"] > 0).mean() * 100
        catalog_score = min(100, max(0, int(profitable_prods)))
    else:
        catalog_score = 80

    # Weighted Overall Score
    health_score = int(round(
        (rev_score * 0.30) + (prof_score * 0.30) + (retention_score * 0.20) + (catalog_score * 0.20)
    ))

    if health_score >= 80:
        status = "Healthy"
    elif health_score >= 60:
        status = "Moderate"
    else:
        status = "At Risk"

    return {
        "health_score": health_score,
        "status": status,
        "components": {
            "revenue_growth": {"score": rev_score, "weight": "30%", "label": "Revenue Trend"},
            "profitability": {"score": prof_score, "weight": "30%", "label": f"Profit Margin ({round(profit_margin, 1)}%)"},
            "retention": {"score": retention_score, "weight": "20%", "label": f"Repeat Customer Rate ({round(repeat_pct, 1)}%)"},
            "catalog_consistency": {"score": catalog_score, "weight": "20%", "label": "Catalog Margin Consistency"},
        },
        "formula_documentation": "Health Score = (Revenue Growth × 0.30) + (Profit Margin × 0.30) + (Customer Retention × 0.20) + (Catalog Consistency × 0.20)",
    }


def generate_business_alerts(df: pd.DataFrame) -> list:
    """Generates automated business anomaly alerts (Sales decline, Churn risk, Growth opportunities)."""
    if df.empty:
        return []

    alerts = []

    # 1. High Churn Risk Alert
    max_date = df["Order_Date"].max()
    cust_last = df.groupby(["Customer_ID", "Customer_Name"])["Order_Date"].max().reset_index()
    cust_last["Recency_Days"] = (max_date - cust_last["Order_Date"]).dt.days
    high_churn = cust_last[cust_last["Recency_Days"] > 90]

    if len(high_churn) > 0:
        names = ", ".join(high_churn["Customer_Name"].head(2).tolist())
        alerts.append({
            "type": "warning",
            "category": "Churn Risk",
            "title": "Customer Inactivity Alert",
            "message": f"{len(high_churn)} customer account{'s' if len(high_churn)>1 else ''} ({names}) inactive > 90 days.",
        })

    # 2. Low Profit Margin Alert
    cat_df = get_sales_by_category(df)
    low_margin = cat_df[cat_df["Profit_Margin_%"] < 20]
    if not low_margin.empty:
        low_cat = low_margin.iloc[0]
        alerts.append({
            "type": "warning",
            "category": "Profitability",
            "title": "Low Category Margin",
            "message": f"{low_cat['Category']} margin is {low_cat['Profit_Margin_%']}%, below the 20% benchmark.",
        })

    # 3. Regional Growth Opportunity
    reg_df = get_sales_by_region(df)
    if not reg_df.empty:
        top_reg = reg_df.iloc[0]
        alerts.append({
            "type": "success",
            "category": "Growth Opportunity",
            "title": "Strong Territory Performance",
            "message": f"{top_reg['Region']} territory is performing strongly with {top_reg['Sales_Share_%']}% revenue share.",
        })

    # 4. Top Product Highlight
    prod_df = get_sales_by_product(df, top_n=1)
    if not prod_df.empty:
        top_p = prod_df.iloc[0]
        alerts.append({
            "type": "info",
            "category": "Catalog Leader",
            "title": "Top Selling Item",
            "message": f"{top_p['Product']} generated highest unit sales across catalog.",
        })

    return alerts


def get_profitability_matrix(df: pd.DataFrame) -> dict:
    """Categorizes products into a 2x2 Profitability Matrix:
    1. High Revenue / High Margin (Stars)
    2. High Revenue / Low Margin (Volume Drivers)
    3. Low Revenue / High Margin (Niche Growth)
    4. Low Revenue / Low Margin (Underperformers)
    """
    if df.empty or "Product" not in df.columns:
        return {"stars": [], "volume_drivers": [], "niche_growth": [], "underperformers": []}

    prod_df = df.groupby("Product").agg(
        Sales=("Sales", "sum"),
        Profit=("Profit", "sum"),
        Quantity=("Quantity", "sum")
    ).reset_index()

    prod_df["Margin_%"] = np.where(
        prod_df["Sales"] > 0, np.round((prod_df["Profit"] / prod_df["Sales"]) * 100, 1), 0.0
    )

    rev_median = prod_df["Sales"].median()
    margin_median = prod_df["Margin_%"].median()

    stars = []
    volume_drivers = []
    niche_growth = []
    underperformers = []

    for _, row in prod_df.iterrows():
        p_info = {
            "Product": row["Product"],
            "Sales": float(row["Sales"]),
            "Profit": float(row["Profit"]),
            "Margin_%": float(row["Margin_%"]),
            "Quantity": int(row["Quantity"]),
        }
        if row["Sales"] >= rev_median and row["Margin_%"] >= margin_median:
            stars.append(p_info)
        elif row["Sales"] >= rev_median and row["Margin_%"] < margin_median:
            volume_drivers.append(p_info)
        elif row["Sales"] < rev_median and row["Margin_%"] >= margin_median:
            niche_growth.append(p_info)
        else:
            underperformers.append(p_info)

    return {
        "revenue_threshold": float(rev_median),
        "margin_threshold": float(margin_median),
        "quadrants": {
            "stars": stars,
            "volume_drivers": volume_drivers,
            "niche_growth": niche_growth,
            "underperformers": underperformers,
        }
    }

